### ISSUE TITLE
Trigger Microsoft Flow US Government flow from SharePoint Lists

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/power-automate-docs#135] opened 2019-07-09 22:28 UTC
Can't find this one on the roadmap.

This is badly needed as it is the only way we know of to implement the lightweight Request sign-off approval Flow. Creating Approvals in the full Flow app requires the Common Data Service, which requires an extra PowerApps or Flow Plan 1 or 2 (as far as we can tell).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Microsoft Flow US Government - Microsoft Flow](https://docs.microsoft.com/en-us/flow/us-govt)
* Content Source: [flow-docs/us-govt.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/us-govt.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by TracyGH** [comment] 2019-12-23 19:56
Yes - agreed!  Right now, there appears to be no O365/modern equivalent for SharePoint 2007/2010/2013 workflows.  The [documentation available](https://docs.microsoft.com/en-us/power-automate/all-assigned-must-approve) does not mention the need for Common Data Service, or the licensing updates.

**Comment by v-aangie** [comment] 2021-06-09 15:15
@sparkitect - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-09 15:15 UTC
Labels: assigned-to-author, doc-bug, doc-enhancement
