### ISSUE TITLE
Instructions do not appear to reflect current iteration of Solutions interface

### ISSUE THREAD

**Issue by elbelcho** [MicrosoftDocs/power-automate-docs#136] opened 2019-07-11 19:44 UTC
There are no user interface elements in PowerApps that allow the user to create a new Process.  They do not appear to exist in the PowerApps solutions explorer or the classic solutions explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in PowerApps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-business-process-flow#feedback)
* Content Source: [flow-docs/create-business-process-flow.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-business-process-flow.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by pganapmsft** [comment] 2020-01-16 18:42
We need to cover this scenario in the documentation - https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/201364/two-options-in-business-process-flow-error-you-have-to-complete-the-required-steps-before-you-can-advance?pifragment-97030=1#responses

Ie: What happens when a boolean field is set as required for a BPF stage? This is a special case and should be documented.

**Comment by v-aangie** [comment] 2021-06-09 15:17
@elbelcho - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-09 15:17 UTC
Labels: assigned-to-author, doc-bug, doc-enhancement
