### ISSUE TITLE
Updating Connection Owner

### ISSUE THREAD

**Issue by gohkohwee** [MicrosoftDocs/power-automate-docs#139] opened 2019-07-16 02:07 UTC
I created a flow and added co-owners to the flow. I'm currently the connection owner. I thought co-owners will be able to switch connector owner. However when they go to the Manage Connections page from the Connection in use, they cannot see my connection in the list but a message saying "You haven't created any connections yet".

Is the connection owner only one able to switch update the account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows#feedback)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by jacobwbutler** [comment] 2020-01-07 02:00
+1

**Comment by Dean-Haas** [comment] 2020-09-14 19:03
@radioblazer Can you please look at this to determine whether a docs update is needed. If this is not a docs issue we can close this issue. 

Customer support is here: https://us.flow.microsoft.com/en-us/support/
Power Automate community forums are here: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity

**Comment by v-aangie** [comment] 2021-06-09 15:18
@gohkohwee - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-09 15:18 UTC
Labels: assigned-to-author, product-feedback
