### ISSUE TITLE
Updating Connection Owner

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/power-automate-docs#150] opened 2019-08-14 12:52 UTC
The instructions appear to be out of date.

There is no option to "Select See all from the OWNERS list"
The only option available is to delete the connection "Search for the connection you want to update, and then select it"
There is not an "... option. "Select ... (more commands), and then select Switch account."

Is the only way now to edit each action in the Flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows#embedded-and-other-connections)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment] 2021-06-21 18:13
@buildbod - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. This article was updated 6/15/2021.  If you're still experiencing the issue described here, please reopen or create a new issue.

cc: @MSFTMan

**Closed by v-aangie** 2021-06-21 18:13 UTC
Labels: assigned-to-author, doc-bug
