### ISSUE TITLE
An example of saving attachments without signatures pictures would be great.

### ISSUE THREAD

**Issue by spyrule** [MicrosoftDocs/power-automate-docs#201] opened 2019-12-24 15:43 UTC
An example of saving all attachements WITHOUT saving signature pictures would be fantastic... there is like 100+ threads about this specific thing, and _none_ of them work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Power Automate](https://docs.microsoft.com/en-us/power-automate/email-triggers#feedback)
* Content Source: [articles/email-triggers.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment] 2020-09-02 16:40
Hi @spyrule. Thanks for your feedback. Can you please point me to a good example of the threads you mention so we can investigate this further? Thanks!

**Comment by Dean-Haas** [comment] 2020-09-22 19:45
@hamenon-ms  Is saving attachments while excluding signature pictures supported, or should this be a feature request?

**Comment by v-aangie** [comment] 2021-06-22 17:04
@spyrule - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-22 17:04 UTC
Labels: doc-enhancement
