### ISSUE TITLE
Missing flowsFilter syntax explanation

### ISSUE THREAD

**Issue by dtriana** [MicrosoftDocs/power-automate-docs#222] opened 2020-02-24 20:02 UTC
The flowsFilter option in the widget settings section https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#widget-settings is not documented, it seems to support a set of filtering functionalities but those are not explained here, plus the sample in the description says flowFilter, it should say flowsFilter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#widget-settings)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by Dean-Haas** [comment] 2020-09-29 22:00
@hamenon-ms & @dblyth-msft , can you please evaluate whether documenting a set of  filtering functionalities for flowsFilter option in the widget settings is needed in this topic? I am working on correcting the second item mentioned. If docs updates are needed, I can help get that done. If not lmk so I can close this one out. Thanks!

**Comment by surjyams** [comment] 2021-04-22 12:01
Do we have updated help files for _flowsFilter_ parameter? Is it possible to somehow use them for templates that use custom connectors?

**Comment by v-aangie** [comment] 2021-06-22 17:12
@dtriana - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. Also, we've corrected the FlowsFilter error. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-22 17:12 UTC
Labels: assigned-to-author, doc-enhancement
