### ISSUE TITLE
Stave fejl

### ISSUE THREAD

**Issue by dancolberg** [MicrosoftDocs/power-automate-docs#482] opened 2021-05-18 11:03 UTC
der er en stave fejl på siden
"Kær skrivebordsflow efter handling"
/Dan

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: b4262ad3-a842-79f1-8ccc-d7bccc8a3d11
* Version Independent ID: 25f9956b-4e90-bef7-95b1-4d7feb33bec2
* Content: [Fejlfinding af et skrivebordsflow - Power Automate](https://docs.microsoft.com/da-dk/power-automate/desktop-flows/debugging-flow)
* Content Source: [articles/desktop-flows/debugging-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/debugging-flow.md)
* Service: **power-automate**
* GitHub Login: @olegmelnykov
* Microsoft Alias: **olmelnyk**

**Comment by v-aangie** [comment] 2021-05-18 20:15
@dancolberg - Thanks for your feedback. We have informed the appropriate team of your issue and will we will soon look into this.

**Comment by v-aangie** [comment] 2021-05-18 20:17
@jowilco - As this appears to be a loc issue, I've assigned it to you. The issue is being closed.

**Closed by v-aangie** 2021-05-18 20:17 UTC

**Comment by jowilco** [comment] 2021-05-31 21:17
@dancolberg 
Tak for din feedback. Vi har opdateret oversættelserne, og de opdaterede oversættelser er live. Lukker dette problem.
