### ISSUE TITLE
Button customization

### ISSUE THREAD

**Issue by iborghoff** [MicrosoftDocs/power-automate-docs#630] opened 2021-12-17 10:43 UTC
It appears that the button customization does not reflect in the report once its Published. I believe this may need adding as a Known Issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a213639f-cfb7-c503-8d6b-b9efc2943ab2
* Version Independent ID: 56ebfc97-1c70-1e34-e56e-104f87a6f064
* Content: [Trigger a cloud flow from any Power BI report - Power Automate](https://docs.microsoft.com/en-us/power-automate/trigger-flow-powerbi-report)
* Content Source: [articles/trigger-flow-powerbi-report.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/trigger-flow-powerbi-report.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment] 2022-03-30 09:31
@hamenon-ms Is this a known issue or by design?

**Comment by MSFTMan** [comment] 2022-04-04 20:42
Confirmed, this is a known issue. We will update the docs. @iborghoff

**Comment by hamenon-ms** [comment] 2022-04-15 21:47
Could you detail out what the issue is? I was able to customize the visualization successfully. Perhaps theres something I'm missing

**Comment by iborghoff** [comment] 2022-04-25 07:40
When a report with the button is published and accessed via PowerBi online, the button loses any visual customizations and defaults to its standard 'look'.

**Comment by MSFTMan** [comment] 2022-05-27 17:47
> When a report with the button is published and accessed via PowerBi online, the button loses any visual customizations and defaults to its standard 'look'.

@hamenon-ms Please see response from @iborghoff

**Comment by hamenon-ms** [comment] 2022-07-19 23:34
@iborghoff just to confirm. This is only with the Power automate visual and works fine with other buttons that you add to the report and publish?

**Comment by iborghoff** [comment] 2022-07-20 08:01
Correct, normal buttons and such work fine once published. It's only the Power Automate visual which doesn't.

**Comment by KendalBond007** [comment] 2023-08-01 21:11
Thanks for contacting us Based on the comments, it appears this issues has been resolved. To contact Support, see here: https://flow.microsoft.com/support/ Closing this issue

**Closed** 2023-08-03 22:03 UTC
Labels: waiting-on-internal-feedback, product-feedback
