### ISSUE TITLE
Upsert with Alternative KEY

### ISSUE THREAD

**Issue by thomassandsor** [MicrosoftDocs/power-automate-docs#167] opened 2019-10-11 08:32 UTC
Instead of having only GUID to match, we should be able to match with Alternative KEY set in CDS. Pretty please? ;) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c3bde-6083-7a7c-3469-48137843198f
* Version Independent ID: d1466842-8d49-67ad-1ca1-326511b2560e
* Content: [Create an automated flow with Common Data Service - Microsoft Flow](https://docs.microsoft.com/en-us/flow/connection-cds#enable-upsert-behavior)
* Content Source: [flow-docs/connection-cds.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/connection-cds.md)
* Service: **flow**
* GitHub Login: @brandonsimons
* Microsoft Alias: **bsimons**

**Comment by v-aangie** [comment] 2021-06-22 16:58
@thomassandsor - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue. Or, for product-related feedback, visit https://ideas.flow.microsoft.com.

**Closed by v-aangie** 2021-06-22 16:58 UTC
Labels: assigned-to-author
