### ISSUE TITLE
The buttons on the card throw an error

### ISSUE THREAD

**Issue by HamishSheild** [MicrosoftDocs/power-automate-docs#127] opened 2019-06-06 09:11 UTC
If you follow these steps and recreate this Flow, then you get an error when either the Snooze or I'll be late buttons are clicked. "Unable to reach app. Please try again."  Is this expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15c461-b88d-7497-cd59-efcd785d5994
* Version Independent ID: 00dd913a-44c7-b407-02c5-528c3b0e7643
* Content: [Learn to create flows that post adaptive cards to Microsoft Teams - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-adaptive-cards-teams)
* Content Source: [flow-docs/create-adaptive-cards-teams.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-adaptive-cards-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by ferrety2006** [comment] 2019-07-23 22:39
Same issue here. The documentation is not providing the info on how to close the loop with Flow so that:
1. Flow waits for the Submit response from the card
2. What JSON is required to ensure the response is getting back to Flow

**Comment by HamishSheild** [comment] 2019-07-24 21:29
Hi @ferrety2006 , from what I have discovered the documentation doesn't close the loop because the response back to the Flow bot is not possible right now.

I watched the session below which is a recording from the Business Applications Summit.  It has a work around that may work for some people by getting the Adaptive Card button to open a PowerApp via a URL.  Within the PowerApp you can then capture input from the user, trigger another Flow etc.

It's not an elegant solution but a good work around while the product team build the capability.

[https://powerusers.microsoft.com/t5/MBAS-Gallery/How-Microsoft-Flow-makes-bots-and-cards-easy-for-everyone/td-p/303801](url)

There is also an idea on the Flow Community portal which you can vote on which 
[https://powerusers.microsoft.com/t5/Flow-Ideas/Trigger-for-when-the-button-pushed-on-the-adaptive-card-on/idc-p/323720#M15454](url)

**Comment by johno-a** [comment] 2019-08-26 20:50
> Hi @ferrety2006 , from what I have discovered the documentation doesn't close the loop because the response back to the Flow bot is not possible right now.
> 
> I watched the session below which is a recording from the Business Applications Summit. It has a work around that may work for some people by getting the Adaptive Card button to open a PowerApp via a URL. Within the PowerApp you can then capture input from the user, trigger another Flow etc.
> 
> It's not an elegant solution but a good work around while the product team build the capability.
> 
> [https://powerusers.microsoft.com/t5/MBAS-Gallery/How-Microsoft-Flow-makes-bots-and-cards-easy-for-everyone/td-p/303801](url)
> 
> There is also an idea on the Flow Community portal which you can vote on which
> [https://powerusers.microsoft.com/t5/Flow-Ideas/Trigger-for-when-the-button-pushed-on-the-adaptive-card-on/idc-p/323720#M15454](url)

None of your links is working

**Comment by HamishSheild** [comment] 2019-08-27 01:47
> Hi @ferrety2006 , from what I have discovered the documentation doesn't close the loop because the response back to the Flow bot is not possible right now.
> I watched the session below which is a recording from the Business Applications Summit. It has a work around that may work for some people by getting the Adaptive Card button to open a PowerApp via a URL. Within the PowerApp you can then capture input from the user, trigger another Flow etc.
> It's not an elegant solution but a good work around while the product team build the capability.
> https://powerusers.microsoft.com/t5/MBAS-Gallery/How-Microsoft-Flow-makes-bots-and-cards-easy-for-everyone/td-p/303801
> There is also an idea on the Flow Community portal which you can vote on which
> https://powerusers.microsoft.com/t5/Flow-Ideas/Trigger-for-when-the-button-pushed-on-the-adaptive-card-on/idc-p/323720#M15454
> 
> None of your links is working

Hmm. not sure why these are not working @johno-a.  If you copy the URL and paste into a browser they work.

**Comment by v-aangie** [comment] 2021-06-09 14:20
@HamishSheild - 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-09 14:20 UTC
Labels: assigned-to-author, doc-enhancement
