### ISSUE TITLE
There is no "process" in the menu

### ISSUE THREAD

**Issue by andifandrich** [MicrosoftDocs/power-automate-docs#133] opened 2019-07-05 06:36 UTC
In the solution's new menu there is no "process" option, so the whole article is useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46309753-0233-f86b-1d82-8c0619c69c88
* Version Independent ID: 4ee6d841-f58f-599d-3e9f-cd91a56a4609
* Content: [Configure actions for workflows in PowerApps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/configure-actions)
* Content Source: [flow-docs/configure-actions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/configure-actions.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by v-aangie** [comment] 2021-06-09 15:13
@andifandrich - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed** 2021-06-09 15:14 UTC
Labels: assigned-to-author, doc-bug
