### ISSUE TITLE
Update Custom connector FAQ with a HTTP 401 troubleshooting.

### ISSUE THREAD

**Issue by danielpetisme** [MicrosoftDocs/power-automate-docs#45] opened 2018-12-06 08:21 UTC
When I create a custom connector based on WebHook, the url provide to my app is URL encoded ("%2F" replaces a "/"). If I use the URL as is to trigger a flow, I get a HTTP 401 Unauthorized.

1- The error code and message are misleading, it suggests a authentication issue where the problem comes from a bad target url.
2- The fix is to decode the URL before usage, IMHO, this trick should be part of the Custom connector FAQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db641f6-e628-7e02-0d9e-a9651dabd5c2
* Version Independent ID: b0ae9c24-f7d6-8f50-0b4b-927c79186748
* Content: [Custom connector content links - Microsoft Flow](https://docs.microsoft.com/en-us/flow/developer/register-custom-api)
* Content Source: [flow-docs/developer/register-custom-api.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/developer/register-custom-api.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment] 2019-03-06 19:47
@mgblythe Hi Michael, do you know who owns updating custom connector docs?

**Comment by MSFTMan** [comment] 2019-03-06 19:48
@danielpetisme Thanks for reporting this issue. We are looking into it.

**Comment by v-aangie** [comment] 2021-06-09 14:15
@danielpetisme - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed** 2021-06-09 14:15 UTC
Labels: assigned-to-author, doc-enhancement, waiting-on-internal-feedback
