### ISSUE TITLE
Please provide a sheet with example data to make this article more useful

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/power-automate-docs#142] opened 2019-07-30 08:45 UTC
There is reference to a spreadsheet that will be provided in later in this article, but it is not provided.
also the examples are screenshots, and this does not allow a copy/paste of the exercises data to excel.

so please provide a sheet with example data to make this article more useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions with conditions. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/use-expressions-in-conditions#feedback)
* Content Source: [flow-docs/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/use-expressions-in-conditions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment] 2021-06-21 18:04
@Josverl - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Comment by Josverl** [comment] 2021-06-22 13:45
well the issue is still quite reproduceable 
![image](https://user-images.githubusercontent.com/981654/122934962-40afe800-d370-11eb-9017-04d565636095.png)

i think the confusion may rise as to the meaning of the word 'Save' in this sentence :
_'Be sure to save your spreadsheet in a location such as Dropbox or Microsoft OneDrive so that Power Automate can access it. '_

My understand from that was that a sample would be provided.
apparently that is not the case, but that a reader is assumed to Create a new spreadsheet

in that case i think the sentence should be 
_'Be sure to create your spreadsheet in a location such as Dropbox or Microsoft OneDrive so that Power Automate can access it. '_

**Comment by Josverl** [comment] 2021-06-22 13:49
I cannot re-open this issue as a repo collaborator closed it

**Comment by v-aangie** [comment] 2021-06-22 16:48
@Josverl - Thanks for your feedback. We have updated the docs to fix information the Prerequisites section, and the updated content will be live today. Re-closing this issue.

**Closed by v-aangie** 2021-06-22 16:48 UTC
Labels: assigned-to-author, doc-bug, resolved
