### ISSUE TITLE
Use information from selected message

### ISSUE THREAD

**Issue by matejskubic** [MicrosoftDocs/power-automate-docs#429] opened 2021-03-04 15:39 UTC
How can I use value from selected message?

I've tried `${$root.entity.teamsFlowRunContext.MessagePayload.Body.PlainText}` but card in Teams does not fill up text from selected message.
![image](https://user-images.githubusercontent.com/839965/109988697-162a1880-7d08-11eb-9b82-61e96c39dd0f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dafbdb-ccd0-0bf2-a83e-f465821a753c
* Version Independent ID: 049c241f-c017-5939-082a-ebbadaf5e4d1
* Content: [Trigger a cloud flow from any message in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/trigger-flow-teams-message)
* Content Source: [articles/trigger-flow-teams-message.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/trigger-flow-teams-message.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by v-aangie** [comment] 2021-06-22 17:07
@matejskubic - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-22 17:07 UTC
Labels: doc-enhancement, product-feedback
