### ISSUE TITLE
Need to add DMG-specific limitations

### ISSUE THREAD

**Issue by jakemannion** [MicrosoftDocs/power-automate-docs#146] opened 2019-07-31 18:04 UTC
There are important limitations using Flow to connect with on-premise applications over a DMG and they are not documented anywhere. I believe this would be a good place to make this information known, so other MS clients don't have to file support tickets and wait to get the answer from the product team.

From Yeiner Lopez (Microsoft):

"As I mentioned to you, from flow perspective the limit is 100mb for an action. This will vary depending on the connector, however, there is a limitation using the gateway, by design this only support 3MB message size."

I suspect that the DMGs can handle larger sizes (I've seen 20 or 30 MB limits mentioned by MS in community forums) and the 3 MB limitation is largely due to chunking. Messages/files over 3MB automatically get chunked when passing from Azure service bus over DMG (to avoid timeouts) and then reassembled at their destination. For many popular on-premise applications (SharePoint 2013/2016/2019) this method is not feasible, and will produce 502 bad gateway errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#feedback)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment] 2020-09-16 02:34
@hamenon-ms Can you please evaluate this doc bug? If valid, please provide the info to me so I can update the doc and close this issue out. Thanks!

**Comment by v-aangie** [comment] 2021-06-21 18:09
@jakemannion - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. This article was updated June 7, 2021. If you're still experiencing the issue described here, please reopen or create a new issue.

cc: @MSFTMan

**Closed by v-aangie** 2021-06-21 18:09 UTC
Labels: assigned-to-author, doc-enhancement
