### ISSUE TITLE
GCC Flow- Common Data Service error

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/power-automate-docs#141] opened 2019-07-17 16:52 UTC
I have a client signed in as their city.gov work credentials to Flow, but when they try to create a trigger "When a new item is created in SharePoint" they get an error at the top of the Flow page when saving, "Failed to create the Common Data Service database in this environment with status code 'ViralServicePlanRequired'". Does the customer need to purchase a single Microsoft Flow/PowerApps Plan 1 US Government license or are there more administrative settings that need to be configured for Flow to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Microsoft Flow US Government - Microsoft Flow](https://docs.microsoft.com/en-us/flow/us-govt#feedback)
* Content Source: [flow-docs/us-govt.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/us-govt.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by derekruss** [comment] 2019-08-07 18:22
It looks like approval isn't available for GCC. 

https://docs.microsoft.com/en-us/connectors/approvals/

**Comment by cpenree** [comment] 2020-04-14 13:43
Is there any timeline for Approvals or the other connectors to become available? Also if Approvals aren't available why do they show up as a connector?

**Comment by v-aangie** [comment] 2021-06-09 15:21
@eschrader - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by v-aangie** 2021-06-09 15:21 UTC
Labels: assigned-to-author, waiting-on-internal-feedback
